
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://mqmpjgxvfvobgebe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xbXBqZ3h2ZnZvYmdjdHJnZWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzQzNTUsImV4cCI6MjA1OTIxMDM1NX0.VZ4Yifkg8mPv2k_HMDyT1pk68fxlDUmxxGrU8jyMyEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
